# Generated by Django 6.0.6 on 2026-07-09 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug (prénom-nom)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('trigramme', models.CharField(blank=True, max_length=10, verbose_name='Trigramme')),
                ('poste', models.CharField(blank=True, max_length=150, verbose_name='Poste')),
                ('xp_duration', models.IntegerField(blank=True, null=True, verbose_name="Durée d'expérience (années)")),
                ('dossier', models.JSONField(blank=True, default=dict, verbose_name='Dossier de compétences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['-updated_at'],
            },
        ),
    ]
