# Generated by Django 6.0.6 on 2026-08-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
    ]
