# Generated by Django 5.1.4 on 2026-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='parcours',
        ),
        migrations.AddField(
            model_name='candidat',
            name='dossier',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dossier de compétences'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='poste',
            field=models.CharField(blank=True, max_length=150, verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='trigramme',
            field=models.CharField(blank=True, max_length=10, verbose_name='Trigramme'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='xp_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name="Durée d'expérience (années)"),
        ),
    ]
