# Generated by Django 5.1.4 on 2026-08-13 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_alter_candidat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
    ]
