# Generated by Django 6.0.6 on 2026-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_remove_candidat_parcours_candidat_dossier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug (prénom-nom)'),
        ),
    ]
