# Generated by Django 6.0.6 on 2026-07-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_candidat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug (prénom-nom)'),
        ),
    ]
